function [ Kesx ] = Stiff_Beam_TVN108_ox( x,Emodule,ISy)
x1=x(1);    x2=x(2);
le=x2-x1;
Kesx =[...
 
[  (12*Emodule*ISy)/le^3,  (6*Emodule*ISy)/le^2, -(12*Emodule*ISy)/le^3,  (6*Emodule*ISy)/le^2];...
[   (6*Emodule*ISy)/le^2,    (4*Emodule*ISy)/le,  -(6*Emodule*ISy)/le^2,    (2*Emodule*ISy)/le];...
[ -(12*Emodule*ISy)/le^3, -(6*Emodule*ISy)/le^2,  (12*Emodule*ISy)/le^3, -(6*Emodule*ISy)/le^2];...
[   (6*Emodule*ISy)/le^2,    (2*Emodule*ISy)/le,  -(6*Emodule*ISy)/le^2,    (4*Emodule*ISy)/le]]; 
end