function [ Kesy ] = Stiff_Beam_TVN108_oy( y,Emodule,ISx)
y1=y(1);    y2=y(2);
le=y2-y1;
Kesy =[...
[  (12*Emodule*ISx)/le^3, -(6*Emodule*ISx)/le^2, -(12*Emodule*ISx)/le^3, -(6*Emodule*ISx)/le^2];...
[  -(6*Emodule*ISx)/le^2,    (4*Emodule*ISx)/le,   (6*Emodule*ISx)/le^2,    (2*Emodule*ISx)/le];...
[ -(12*Emodule*ISx)/le^3,  (6*Emodule*ISx)/le^2,  (12*Emodule*ISx)/le^3,  (6*Emodule*ISx)/le^2];...
[  -(6*Emodule*ISx)/le^2,    (2*Emodule*ISx)/le,   (6*Emodule*ISx)/le^2,    (4*Emodule*ISx)/le]];

end